library(ggplot2)
library(gtable)
rm(list=ls())
data = read.csv('temp.txt', sep = '\t' , header=T)
graphDisplacement = ggplot(data, aes(Time, Displacement, col=Label)) + geom_line(aes(linetype=Label), size = 0.5) + ggtitle("N:1000, Time:2000, Species Num:100, Param:r;20;20;0.5_")
scale_linetype_manual(values=c('dotdash', 'dotted')) 
graphR = ggplot(data, aes(Time, R, col=Label)) + geom_line( se=F)
graphU = ggplot(data, aes(Time, U, col=Label)) + geom_line( se=F)
graphVelocity = ggplot(data, aes(Time, Velocity, col=Label)) + geom_line( se=F)
graphAcceleration = ggplot(data, aes(Time, Acceleration, col=Label)) + geom_line()
graphVariance = ggplot(data, aes(Time, Variance, col=Label)) + geom_line()
grphD = ggplotGrob(graphDisplacement)
grphR = ggplotGrob(graphR)
grphU = ggplotGrob(graphU)
grphVel = ggplotGrob(graphVelocity)
grphAccel = ggplotGrob(graphAcceleration)
grphVar = ggplotGrob(graphVariance)
grid.draw(rbind(grphD, grphR, grphU, size = "first")) 
grid.newpage()
grid.draw(rbind(grphVel, grphAccel, grphVar, size = "first")) 
